1682 feedback python
Microsoft/WebTemplateStudio pull request #1686
Opened 2020-11-26 17:15 UTC by dgomezc

## PR checklist

- Quick summary of changes
  - Refactor flask templates
- Which issue does this PR relate to?
#1682 - Feedback on generated Python code

2020-11-30 12:58 UTC, prupipho commented on templates/Web/_composition/Flask/Page.Flask.List.AddRoutes/backend/server_postaction.py
> +            {"error": "Could not find an item with the given id"}
maybe this could be a constants too?

2020-11-30 13:07 UTC, prupipho reviewed
All looking good so far. Gonna test it now.

2020-12-03 16:32 UTC, prupipho submitted a review, later dismissed
Tested and reviewed

2020-12-03 17:49 UTC, prupipho approved these changes, later dismissed

2020-12-22 17:23 UTC, sibille requested changes
After adding the server to src, the app does not start when published to azure app service

2021-01-11 14:46 UTC, sibille approved these changes

2021-01-11 14:47 UTC, merged